### PR TITLE
Added @modifiers annotation

### PR DESCRIPTION
**Pull request by Rhym**
Added the @modifiers annotation tag. This can be used to list out class modifiers in the documentation.

### CODE REVIEW

**Comment by Rhym** [comment]
Screenshot of modifiers in the wild:

screenshot

**Comment by Rhym** [comment]
Any chance of taking a look at this, @michaelseibt :champagne:

**Comment by pkkummermo** [comment]
Anyone looking into this? I'm basically waiting until it's entering master before I start using Nucleus fully :)

**Comment by Rhym** [comment]
@michaelseibt Cheers, man. Can you do a NPM version bump please? 🎉 🎉 🍾

**Comment by michaelseibt** [comment]
Merged, bumped and published!

**Comment by Rhym** [comment]
@michaelseibt Yay! I think I may do some work on the mobile styling next year, maybe a button that emulates sizes.

**Comment by pkkummermo** [comment]
Nice, great feature :+1:

**Comment by michaelseibt** [comment]
> maybe a button that emulates sizes.

Great idea! http://demo.patternlab.io/?p=viewall-organisms-comments has this kind of feature and i also fancy the "random viewport size" button.

**Pull request merged**
