### PR TITLE
Added support for @script annotation tag

### PR DESCRIPTION
**Pull request by jcfariadias**
Hello,

I needed to create a style guide where I could be able to indicate whether that particular part (atom/molecule/structure) needed to be complemented with javascript code to run.

Therefore I added support for a @script tag that will render in a code block, just below the markup.

Example:

``` CSS
/**
 * Header bar with logo, navigation, and tool icons at the top of the page.
 *
 * @structure Header
 * @flag full-width
 * @markup
 *  <div class="SG-header">
 *    @{include:.SG-logo}
 *    @{include:.SG-nav-icons}
 *    @{include:.SG-nav}
 *  </div>
 * @script
 *    $('body').on('click','.SG-header',function(){
 *        $(this).doSomething();
 *    });
 */
```

Will make the styleguide render this

captura de ecra 2016-08-24 as 14 47 58

This can be applied to Atoms, Molecules and Structures. I think nuclides, and their special forms (mixins and colors) step out of this specific need so I intentionaly left them out of this feature.

Tested with Google Chrome 52.0.2743.116 (64-bit) on a MacOS OSX Yosemite (10.10)

### CODE REVIEW

**Comment by jcfariadias** [comment]
Extended features and fixed tests not running successfuly

Ability to specify tag ``scripts`` in ``config.nucleus.json``, pointing to javascript sources, needed to run javascript based componentes in the styleguide

Example config 
```JSON
{
  "title":  "Nucleus",
  "files":  [
    "assets/styles/**/*.scss",
    "assets/styles/nuclides/icons.css",
    "docs/src/styles/nuclides/icons.css",
    "docs/src/styles/**/*.scss"
  ],
  "css": "../docs/build/styles/app.css",
  "target"  : "./styleguide",
  "namespace": null,
  "scripts" : ["//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js","./scripts/ui-kit.js"]
}
```

**Comment by memic84** [comment]
Will there be any development soon on this pull request? This feature would be really useful!

**Comment by jcfariadias** [comment]
@memic84 ASAP I'll merge latest branch

**Comment by michaelseibt** [comment]
If you'd resolve the conflicts, I'd be happy to merge this, too :)

**Comment by memic84** [comment]
I'll take a loot, as soon as i have time.

- Sead Memi*ć*

2016-12-16 11:37 GMT+01:00 Michael Seibt <notifications@github.com>:

**Comment by pieplu** [comment]
@michaelseibt, conflict resolved :)

**Comment by jcfariadias** [comment]
Hi
@michaelseibt , any forecast on when this could be merged to master? I'm using a link to my github account in the npm packages, and would really like to have the official repo instead

Thanks!

**Comment by pieplu** [comment]
I use the same workaround... ^^

**Comment by michaelseibt** [comment]
Merged 🎉  thanks for the collaboration!

**Comment by michaelseibt** [comment]
Bumped, you folks should upgrade to 1.1.0 👍

**Pull request merged**
